site:
    title: IRCHelp.org
    description: Comprehensive information on everything Internet Relay Chat
    author: irchelpers
    pretty_urls: false
    
smartypants:
    enable: true

baker:
    skip_patterns:
        - /^index.php/

