title: IRCHelp.org

email: support@irchelp.org

description: Information related to IRC

baseurl: ""

url: http://www.irchelp.org

twitter_username: ""

github_username:  irchelp

gems:
  - jekyll-redirect-from
  - jekyll-sitemap

markdown: kramdown
