# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: IRCHelp.org
email: support@irchelp.org
description: > # this means to ignore newlines until "baseurl:"
  irchelp.org is a website about the workings of IRC for both newbies and
  experts alike. It exists since 1996, but has recently been converted to
  jekyll.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.irchelp.org" # the base hostname & protocol for your site
#twitter_username:
github_username:  irchelp
plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
# Build settings
markdown: kramdown
